export const sliderData =   [
    {
      "img1": "https://m.media-amazon.com/images/I/61oNTRtzcQL._AC_UL480_FMwebp_QL65_.jpg",
      "img2": "https://m.media-amazon.com/images/I/61+6TMO6eiL._SX679_.jpg",
      "img3": "https://m.media-amazon.com/images/I/61swvPJ9fLL._SX679_.jpg",
      "img4": "https://m.media-amazon.com/images/I/61eny2HoR4L._SX679_.jpg",
      "video": "https://m.media-amazon.com/images/I/61oNTRtzcQL._AC_UL480_FMwebp_QL65_.jpg",
      "title": "KAMA ROSE LIP BALM",
      "cost": "₹598",
      "location": "New Delhi",
      "distance": "47 km",
      "description": "A luxurious rose-scented lip balm enriched with natural oils to keep your lips soft and hydrated."
    },
    
    {
      "img1": "https://www.sephora.com/productimages/sku/s2495497-main-zoom.jpg?imwidth=1224",
      "img2": "https://www.sephora.com/productimages/sku/s2495497-av-16-zoom.jpg?imwidth=1224",
      "img3": "https://www.sephora.com/productimages/sku/s2495497-av-12-zoom.jpg?imwidth=1224",
      "img4": "https://www.sephora.com/productimages/sku/s2495497-av-19-zoom.jpg?imwidth=1224",
      "video": "",
      "title": "Lip Butter Balm for Hydration & Shine",
      "cost": "₹4253",
      "location": "Hyderabad",
      "distance": "23 km",
      "description": "A luxurious rose-scented lip balm enriched with natural oils to keep your lips soft and hydrated.."
    },
    {
      "img1": "https://m.media-amazon.com/images/I/71gS-slF6jL._SL1500_.jpg",
      "img2": "https://m.media-amazon.com/images/I/81p5+bNI0ZL._SL1500_.jpg",
      "img3": "https://m.media-amazon.com/images/I/81CS-aMFzCL._SL1500_.jpg",
      "img4": "https://m.media-amazon.com/images/I/7156frgektL._SL1500_.jpg",
      "video": "https://m.media-amazon.com/images/I/618lxX-vcTL._SX679_.jpg",
      "title": "Gold Bond Age Renew Neck & Chest Firming Age Renew Cream, 2 oz., Clinically Tested Skin Firming Cream",
      "cost": "₹4886",
      "location": "Kolkata",
      "distance": "33 km",
      "description": "Perfect for daily use, this 2 oz. cream is lightweight, non-greasy, and absorbs quickly for a comfortable, refreshed feel."
    },
    {
      "img1": "https://www.srisritattva.com/cdn/shop/products/Tulasi-tablet_f5144a49-b8a9-4408-a29d-61970d141524.jpg?v=1606909543&width=1445",
      "img2": "https://www.srisritattva.com/cdn/shop/files/1-43.jpg?v=1699447254",
      "img3": "https://www.srisritattva.com/cdn/shop/files/1-44.jpg?v=1699447254",
      "img4": "https://m.media-amazon.com/images/I/81T-VNf4BDL._AC_SX679_.jpg",
      "video": "https://m.media-amazon.com/images/I/81T-VNf4BDL._AC_SX679_.jpg",
      "title": "Tulasi - Cold & Cough, 60 Tabs | 500mg",
      "cost": "₹3971",
      "location": "Chennai",
      "distance": "9 km",
      "description": "Sri Sri Tattva Tulasi tablets (500mg, 60 tabs) provide natural relief from cold and cough symptoms, supporting respiratory health and immunity.."
    },
    {
      "img1": "https://www.daburshop.com/cdn/shop/files/1_9c5b39b9-0b96-4852-80e5-a4c9a7a4f7d1_1024x1024.png?v=1733211474",
      "img2": "https://www.daburshop.com/cdn/shop/files/1_562cf769-ec10-475d-a79f-8846f3a8b738_1024x1024.png?v=1730805540",
      "img3": "https://www.daburshop.com/cdn/shop/files/3_00a460cb-d939-49f0-ab21-663f032babba_1024x1024.jpg?v=1730108952",
      "img4": "https://www.daburshop.com/cdn/shop/files/2_4daf6680-4e36-4c81-8189-6850b4e6567b_1024x1024.jpg?v=1730108953",
      "video": "https://m.media-amazon.com/images/I/61S5qtPqyBL._SX679_.jpg",
      "title": "Dabur Herb'l Clove Cavity Protection Toothpaste - 200g",
      "cost": "₹2949",
      "location": "Ahmedabad",
      "distance": "1 km",
"description": "Dabur Herb'l Clove toothpaste (200g) protects against cavities with clove's natural antibacterial power.."
    },
    {
      "img1": "https://www.daburshop.com/cdn/shop/files/1_251609c0-f104-4678-a299-6696889a4afa_1024x1024.png?v=1733211467",
      "img2": "https://www.daburshop.com/cdn/shop/files/2_fe1a0114-9241-487b-9fd4-6b9f8a64a8e6_1024x1024.jpg?v=1730108747",
      "img3": "https://www.daburshop.com/cdn/shop/files/2_fe1a0114-9241-487b-9fd4-6b9f8a64a8e6_1024x1024.jpg?v=1730108747",
      "img4": "https://www.daburshop.com/cdn/shop/files/5_5b381990-d66c-4933-b667-0b8702fa4edb_1024x1024.jpg?v=1730108748",
      "video": "https://m.media-amazon.com/images/I/6108uSkJQKL._SX679_.jpg",
      "title": "Dabur Gulabari Rose Glow Cleanser - 100ml",
      "cost": "₹4492",
      "location": "Kolkata",
      "distance": "30 km",
      "description": "Dabur Gulabari Rose Glow Cleanser (100ml): Cleanses and adds a natural rose glow to your skin."
    },
    
    {
      "img1": "https://www.daburshop.com/cdn/shop/files/71p0DDw7-VL._SL1500_1024x1024.png?v=1733210268",
      "img2": "https://www.daburshop.com/cdn/shop/files/3_a1396938-1ee8-46de-b0dc-281ad1333d63_1024x1024.jpg?v=1729834561",
      "img3": "https://www.daburshop.com/cdn/shop/files/4_d93bf324-4831-4451-84c7-0cbdf0aa3eea_1024x1024.jpg?v=1729834560",
      "img4": "https://www.daburshop.com/cdn/shop/files/5_bf0187fa-d8cc-4a48-b359-4732638bf6c3_1024x1024.jpg?v=1729834560",
      "video": "https://m.media-amazon.com/images/I/61RitVgCGML._SX679_.jpg",
      "title": "Dabur Chyawanprash | 3X Immunity Action | Builds Strength, Stamina & Overall Health - 2kg",
      "cost": "₹1899",
      "location": "Chennai",
      "distance": "41 km",
      "description": "Dabur Chyawanprash (2kg): Boosts immunity, strength, stamina, and overall health with a 3X action formula."
    },
    {
      "img1": "https://www.daburshop.com/cdn/shop/files/0_c119eb95-fc93-4242-be55-d8f1abafde02_1024x1024.png?v=1735883743",
      "img2": "https://www.daburshop.com/cdn/shop/files/1_1c46b6c5-07db-4efb-b652-6ee2b25da0a7_1024x1024.png?v=1730810064",
      "img3": "https://www.daburshop.com/cdn/shop/files/3_cebfacae-95e4-4440-bbdc-f6a9b22b72cc_1024x1024.png?v=1729670255",
      "img4": "https://www.daburshop.com/cdn/shop/files/4_121e97d2-333e-4350-878e-a49e26ea4d72_1024x1024.png?v=1729670258",
      "video": "https://m.media-amazon.com/images/I/71GM3LR4cCL._SX679_.jpg",
      "title": "Dabur Amla Hair Oil - 550ml",
      "cost": "₹2074",
      "location": "Lucknow",
      "distance": "4 km",
      "description": "Dabur Amla Hair Oil (550ml): Nourishes and strengthens hair for healthy growth."
    },
    {
      "img1": "https://m.media-amazon.com/images/I/81V7H4Fc+-L._AC_SX679_.jpg",
      "img2": "https://m.media-amazon.com/images/I/71+PdzwliqL._AC_SX679_.jpg",
      "img3": "https://m.media-amazon.com/images/I/71psJ8HGIpL._AC_SX679_.jpg",
      "img4": "https://m.media-amazon.com/images/I/71mHgyLsQrL._AC_SL1500_.jpg",
      "video": "https://m.media-amazon.com/images/I/81rTMrNxnEL._SX679_.jpg",
      "title": "Herbal and Ayurvedic Neem Karela Jamun Juice 500ml",
      "cost": "₹3915",
      "location": "Chennai",
      "distance": "48 km",
      "description": "Neem Karela Jamun Juice (500ml): A herbal Ayurvedic blend for blood sugar management and overall health.."
    }
  ]

  export const  dataCategory =  [
    {
      title: "Health Care",
      img: "https://www.patanjaliayurved.net/media/images/health-care.webp",
    },
    {
      title: "Personal Care",
      img: "https://www.patanjaliayurved.net/media/images/personal-care.webp",
    },
    {
      title: "Medicine",
      img: "https://www.patanjaliayurved.net/media/images/medicine.webp",
    },
    {
      title: "Nutraceuticals",
      img: "https://www.patanjaliayurved.net/media/images/nutraceuticals.webp",
    },
    {
      title: "Paridhan",
      img: "https://www.patanjaliayurved.net/media/images/paridhan-a.webp",
    },
    {
      title: "Hawan Samagri",
      img: "https://www.patanjaliayurved.net/media/images/Hawan_samagr_icon.webp",
    },
  ];


  export const companyIcons = [
    { name: "Sri Sri Tattva", iconUrl: "https://imgs.search.brave.com/1oTnuNSENlNgAs3ehhOqFJnXTe16VC4K30fhpcinYY8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9kMTAx/MWowbGJ2NWsxdS5j/bG91ZGZyb250Lm5l/dC9hc3NldHMvc3Rv/cmUtNDk1ODA4LzQ5/NTgwOC1sb2dvLTE1/NTY2MzM1MzYuanBn" },
    { name: "Kerala Ayurveda Ltd", iconUrl: "https://imgs.search.brave.com/1PXHvPMtnFK_QZ0c-E_y34ho99534lH4jh5LdfwNJ5c/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/a2FpcmFsaS5jb20v/aW1hZ2VzL2Zvb3Rs/b2dvLnBuZw" },
    { name: "Emami Group", iconUrl: "https://imgs.search.brave.com/aczlqk9zhlgzEKMbQlV0IaPi92WviBnOHNaqYT27DaU/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZW1hbWlsdGQuaW4v/d3AtY29udGVudC91/cGxvYWRzLzIwMjMv/MTAvMTgyMTU5MjYv/c3Rhcm1hcmtfbG9n/b3MucG5n" },
    { name: "Vicco Laboratories", iconUrl: "https://imgs.search.brave.com/OKifm7ojRtV75mM_8k1x5E1sUbWi3FH6PFEPaS8gLa0/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly8xMmMz/bjFkbS5jZG4uaW1n/ZW5nLmluLy9tZWRp/YS9tZ3NfYnJhbmQv/di9pL3ZpY2NvX2xv/Z29fMS5qcGc" },
    { name: "Charak Pharma", iconUrl: "https://imgs.search.brave.com/BFCumPKpc2tuvGVps_l3Xm-3v8AIiYY907u5C9Znpw0/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/Y2FsZGlhbG9ndWVz/LmluL2gtdXBsb2Fk/LzIwMjIvMTAvMjQv/MTg4OTEwLWluZGV4/LndlYnA" },
    { name: "Zandu Ayurveda", iconUrl: "https://imgs.search.brave.com/175oSi9ShNO1C_gFnFwIi6T4Khn2nGBoBOYEz38S2yM/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL1Mv/c3RvcmVzLWltYWdl/LXVwbG9hZHMtZXUt/cHJvZC81L0FtYXpv/blN0b3Jlcy9BMjFU/SlJVVU40S0dWL2Jm/YWVjNjEyMTE1ZDIx/ODBjMjZjYWM5M2U1/YTM0ZDFiLnc0MDAu/aDQwMC5fQ1IwLDAs/NDAwLDQwMF9TWDEw/MF8uanBn" },
    { name: "Baidyanath Group", iconUrl: "https://imgs.search.brave.com/kCjbe0_b27sPXUA9RI3C825TJJVRvYqjXtQBY7bK_a0/rs:fit:500:0:0:0/g:ce/aHR0cDovL2F5dXJ3/aWtpLm9yZy9pbWFn/ZXMvNC80OC9CYWlk/eWFuYXRoX2xvZ28u/anBn" },
    { name: "Himalaya Wellness Company", iconUrl: "https://imgs.search.brave.com/Q91TWUcRHLsRHf9oN7MeVPyzJhXfrf6kbi6LZtDQs14/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9icmFu/ZGxvZ29zLm5ldC93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyMi8w/Ny9oaW1hbGF5YV93/ZWxsbmVzcy1sb2dv/X2JyYW5kbG9nb3Mu/bmV0X3AwaHRnLTUx/Mng1MTIucG5n" },
    { name: "Patanjali Ayurved", iconUrl: "https://imgs.search.brave.com/5WW8g-ltlbgcA9YkbiF9_alviMSWrgK9cI0iXljrOhs/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMud2lraWEubm9j/b29raWUubmV0L2xv/Z29wZWRpYS9pbWFn/ZXMvZC9kYy9QYXRh/bmphbGkucG5nL3Jl/dmlzaW9uL2xhdGVz/dC9zY2FsZS10by13/aWR0aC1kb3duLzIw/MD9jYj0yMDIwMDQy/ODA2MTIxMQ.jpeg" },
    { name: "Dabur", iconUrl: "https://imgs.search.brave.com/Q6B3ilPZdc-0fmjWCiYe0isuQvpdBRkhoQuwDlTFh1k/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/bG9nby53aW5lL2Ev/bG9nby9EYWJ1ci9E/YWJ1ci1Mb2dvLndp/bmUuc3Zn" }
  ];
  

  export const cardsData = [
    {
      img: "https://m.media-amazon.com/images/I/61oNTRtzcQL._AC_UL480_FMwebp_QL65_.jpg",
      title: "KAMA ROSE LIP BALM",
      cost: "₹598",
      location: "New Delhi",
      distance: "47 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/51RruV8mhfL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Lip Balm",
      cost: "₹4253",
      location: "Hyderabad",
      distance: "23 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/618lxX-vcTL._SX679_.jpg",
      title: "Ayurveda: Ancient Healing Science",
      cost: "₹4886",
      location: "Kolkata",
      distance: "33 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/511emskZ4yL._SX679_.jpg",
      title: "Ceramide Lip Balm",
      cost: "₹3971",
      location: "Chennai",
      distance: "9 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61S5qtPqyBL._SX679_.jpg",
      title: "Ilerbal Lip Balm",
      cost: "₹2949",
      location: "Ahmedabad",
      distance: "1 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/6108uSkJQKL._SX679_.jpg",
      title: "BENEFITS",
      cost: "₹4492",
      location: "Kolkata",
      distance: "30 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61RitVgCGML._SX679_.jpg",
      title: "Hero Ingredient Lip Balm",
      cost: "₹1899",
      location: "Chennai",
      distance: "41 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/71GM3LR4cCL._SX679_.jpg",
      title: "Sesa Ayurvedic Oil",
      cost: "₹2074",
      location: "Lucknow",
      distance: "4 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/81rTMrNxnEL._SX679_.jpg",
      title: "JAMUN NEEM KARELA Juice",
      cost: "₹3915",
      location: "Chennai",
      distance: "48 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61aJ8Z9ZzZL._SX679_.jpg",
      title: "Turmeric Face Cream",
      cost: "₹899",
      location: "Mumbai",
      distance: "12 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61bJZ9Z9ZzZL._SX679_.jpg",
      title: "Aloe Vera Gel",
      cost: "₹499",
      location: "Bangalore",
      distance: "5 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61cJZ9Z9ZzZL._SX679_.jpg",
      title: "Neem Face Wash",
      cost: "₹299",
      location: "Pune",
      distance: "8 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61dJZ9Z9ZzZL._SX679_.jpg",
      title: "Sandalwood Soap",
      cost: "₹199",
      location: "Jaipur",
      distance: "15 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61eJZ9Z9ZzZL._SX679_.jpg",
      title: "Rose Water Toner",
      cost: "₹399",
      location: "Chandigarh",
      distance: "20 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61fJZ9Z9ZzZL._SX679_.jpg",
      title: "Honey Face Mask",
      cost: "₹599",
      location: "Indore",
      distance: "25 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61gJZ9Z9ZzZL._SX679_.jpg",
      title: "Lavender Essential Oil",
      cost: "₹799",
      location: "Bhopal",
      distance: "30 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61hJZ9Z9ZzZL._SX679_.jpg",
      title: "Tea Tree Oil",
      cost: "₹699",
      location: "Nagpur",
      distance: "35 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61iJZ9Z9ZzZL._SX679_.jpg",
      title: "Coconut Hair Oil",
      cost: "₹499",
      location: "Surat",
      distance: "40 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61jJZ9Z9ZzZL._SX679_.jpg",
      title: "Amla Shampoo",
      cost: "₹399",
      location: "Vadodara",
      distance: "45 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61kJZ9Z9ZzZL._SX679_.jpg",
      title: "Bhringraj Hair Oil",
      cost: "₹599",
      location: "Visakhapatnam",
      distance: "50 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61lJZ9Z9ZzZL._SX679_.jpg",
      title: "Argan Hair Serum",
      cost: "₹899",
      location: "Thane",
      distance: "55 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61mJZ9Z9ZzZL._SX679_.jpg",
      title: "Saffron Face Cream",
      cost: "₹999",
      location: "Patna",
      distance: "60 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61nJZ9Z9ZzZL._SX679_.jpg",
      title: "Vitamin C Serum",
      cost: "₹1299",
      location: "Ghaziabad",
      distance: "65 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61oJZ9Z9ZzZL._SX679_.jpg",
      title: "Charcoal Face Mask",
      cost: "₹499",
      location: "Ludhiana",
      distance: "70 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61pJZ9Z9ZzZL._SX679_.jpg",
      title: "Oatmeal Body Scrub",
      cost: "₹699",
      location: "Agra",
      distance: "75 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61qJZ9Z9ZzZL._SX679_.jpg",
      title: "Shea Butter Lotion",
      cost: "₹899",
      location: "Nashik",
      distance: "80 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61rJZ9Z9ZzZL._SX679_.jpg",
      title: "Peppermint Foot Cream",
      cost: "₹399",
      location: "Faridabad",
      distance: "85 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61sJZ9Z9ZzZL._SX679_.jpg",
      title: "Eucalyptus Oil",
      cost: "₹299",
      location: "Meerut",
      distance: "90 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61tJZ9Z9ZzZL._SX679_.jpg",
      title: "Lemongrass Hand Cream",
      cost: "₹499",
      location: "Rajkot",
      distance: "95 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61uJZ9Z9ZzZL._SX679_.jpg",
      title: "Jasmine Perfume Oil",
      cost: "₹799",
      location: "Kalyan",
      distance: "100 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61vJZ9Z9ZzZL._SX679_.jpg",
      title: "Sandalwood Perfume",
      cost: "₹899",
      location: "Vasai",
      distance: "105 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61wJZ9Z9ZzZL._SX679_.jpg",
      title: "Rose Perfume Oil",
      cost: "₹999",
      location: "Varanasi",
      distance: "110 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61xJZ9Z9ZzZL._SX679_.jpg",
      title: "Lavender Perfume",
      cost: "₹1099",
      location: "Srinagar",
      distance: "115 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61yJZ9Z9ZzZL._SX679_.jpg",
      title: "Patchouli Perfume Oil",
      cost: "₹1199",
      location: "Aurangabad",
      distance: "120 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61zJZ9Z9ZzZL._SX679_.jpg",
      title: "Ylang Ylang Perfume",
      cost: "₹1299",
      location: "Dhanbad",
      distance: "125 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61AJZ9Z9ZzZL._SX679_.jpg",
      title: "Vanilla Perfume Oil",
      cost: "₹1399",
      location: "Amritsar",
      distance: "130 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61BJZ9Z9ZzZL._SX679_.jpg",
      title: "Bergamot Perfume",
      cost: "₹1499",
      location: "Allahabad",
      distance: "135 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61CJZ9Z9ZzZL._SX679_.jpg",
      title: "Ginger Perfume Oil",
      cost: "₹1599",
      location: "Ranchi",
      distance: "140 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61DJZ9Z9ZzZL._SX679_.jpg",
      title: "Cinnamon Perfume",
      cost: "₹1699",
      location: "Coimbatore",
      distance: "145 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61EJZ9Z9ZzZL._SX679_.jpg",
      title: "Clove Perfume Oil",
      cost: "₹1799",
      location: "Jabalpur",
      distance: "150 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61FJZ9Z9ZzZL._SX679_.jpg",
      title: "Cardamom Perfume",
      cost: "₹1899",
      location: "Gwalior",
      distance: "155 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61GJZ9Z9ZzZL._SX679_.jpg",
      title: "Nutmeg Perfume Oil",
      cost: "₹1999",
      location: "Vijayawada",
      distance: "160 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61HJZ9Z9ZzZL._SX679_.jpg",
      title: "Orange Perfume",
      cost: "₹2099",
      location: "Jodhpur",
      distance: "165 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61IJZ9Z9ZzZL._SX679_.jpg",
      title: "Lemon Perfume Oil",
      cost: "₹2199",
      location: "Madurai",
      distance: "170 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61JJZ9Z9ZzZL._SX679_.jpg",
      title: "Grapefruit Perfume",
      cost: "₹2299",
      location: "Raipur",
      distance: "175 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61KJZ9Z9ZzZL._SX679_.jpg",
      title: "Peppermint Perfume Oil",
      cost: "₹2399",
      location: "Kota",
      distance: "180 km",
    },
    {
      img: "https://m.media-amazon.com/images/I/61LJZ9Z9ZzZL._SX679_.jpg",
      title: "Eucalyptus Perfume",
      cost: "₹2499",
      location: "Guwahati",
      distance: "185 km",
    },
  ];
  